### ISSUE TITLE
_init_.py path error in macOs Big Sur 11.6:

### ISSUE THREAD

**Issue by BryanZhu-Us** [lordloki/EasyOnline#3]
path error in macOs Big Sur 11.6:
path = os.path.dirname(os.path.abspath(__file__))+"\\"+script_name

This can run：
path = os.path.dirname(os.path.abspath(__file__)) + '/'+script_name

**Comment by DonFlymoor** [comment]
Fixed by #4

**Comment by lordloki** [comment]
Fix commit it. Thanks!!!
